safe: true
lsi: false
pygments: true
permalink: /posts/:title
name: Keijiro Takahashi
url: http://keijiro.github.io
description: Some articles
twitter: _kzr
github: keijiro
gravatar_url: http://gravatar.com/avatar/13ffb6ada421d0d4731b5ed35d694191
